KTU\CountersBundle\Entity\Counters:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [url]
            message: counters.constraints.message
            groups: [create]
    properties:
        cat:
            - NotBlank:
                message: counters.cat.not_blank.message
                groups: [create,edit]
        name:
            - NotBlank:
                message: counters.name.not_blank.message
                groups: [create,edit]
            - Length:
                max: 100
                maxMessage: counters.name.length.message
                groups: [create,edit]
        url:
            - Notblank:
                message: counters.url.not_blank.message
                groups: [create,edit]
            - Length:
                max: 45
                maxMessage: counters.url.length.message
                groups: [create,edit]
            - Regex:
                pattern: '/^https?:\/\//'
                match: false
                message: counters.url.regex.message
                groups: [create,edit]
        counterdesc:
            - Notblank:
                message: counters.counterdesc.not_blank.message
                groups: [create,edit]
        backgroundColor:
            - Notblank:
                message: counters.backgroundColor.not_blank.message
                groups: [editColors]
            - Regex:
                pattern: '/^#[A-Fa-f0-9]{6}$/'
                match: true
                message: counters.backgroundColor.regex.message
                groups: [editColors]
        borderColor:
            - Notblank:
                message: counters.borderColor.not_blank.message
                groups: [editColors]
            - Regex:
                pattern: '/^#[A-Fa-f0-9]{6}$/'
                match: true
                message: counters.borderColor.regex.message
                groups: [editColors]
        textColor:
            - Notblank:
                message: counters.textColor.not_blank.message
                groups: [editColors]
            - Regex:
                pattern: '/^#[A-Fa-f0-9]{6}$/'
                match: true
                message: counters.textColor.regex.message
                groups: [editColors]
        uniqueColor:
            - Notblank:
                message: counters.uniqueColor.not_blank.message
                groups: [editColors]
            - Regex:
                pattern: '/^#[A-Fa-f0-9]{6}$/'
                match: true
                message: counters.uniqueColor.regex.message
                groups: [editColors]
        totalColor:
            - Notblank:
                message: counters.totalColor.not_blank.message
                groups: [editColors]
            - Regex:
                pattern: '/^#[A-Fa-f0-9]{6}$/'
                match: true
                message: counters.totalColor.regex.message
                groups: [editColors]
        barTotalColor:
            - Notblank:
                message: counters.barTotalColor.not_blank.message
                groups: [editColors]
            - Regex:
                pattern: '/^#[A-Fa-f0-9]{6}$/'
                match: true
                message: counters.barTotalColor.regex.message
                groups: [editColors]
        barUniqueColor:
            - Notblank:
                message: counters.barUniqueColor.not_blank.message
                groups: [editColors]
            - Regex:
                pattern: '/^#[A-Fa-f0-9]{6}$/'
                match: true
                message: counters.barUniqueColor.regex.message
                groups: [editColors]